### PR TITLE
Fixed incorrect variable in curl.py file

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolve the issue #266 .

### CODE REVIEW

**Comment by introkun** [comment]
@96RadhikaJadhav please check other mentions of 'sz' variable in the method you've updated. Your fiz is not complete unfortunately.

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav please check other mentions of 'sz' variable in the method you've updated. Your fiz is not complete unfortunately.

@introkun Could you please check now.

**Review by introkun — APPROVED** [review]
lgtm

**Comment by introkun** [comment]
@all-contributors please add @96RadhikaJadhav for code

**Pull request merged**
