### PR TITLE
Added correct sorting by file size (fixes #129)

### LINKED ISSUE #129: Nut's sort by Size is alphabetic instead of numerical
In nut (at least the Windows exe), if you sort files by size, it sorts the file sizes alphabetically instead of numerically

### PR DESCRIPTION
**Pull request by introkun**
* added user friendly file size formatting for files at UI

### CODE REVIEW

**Comment by blawar** [comment]
What is up with the "i" in the units?  Is it a foreign language thing?  "['Ki','Mi','Gi','Ti','Pi','Ei','Zi']".

**Comment by blawar** [comment]
I have not ran the code, but I reviewed it and it looks good.

**Comment by introkun** [comment]
@blawar i shows that its about bytes, not about numbers. Since kilo is ftom ISO and means 1000, not 1024 as in CS. You can read about it here https://en.wikipedia.org/wiki/Binary_prefix

**Comment by blawar** [comment]
Ah that ambiguity.  The changes look good.  And yes, fixing that sort was a pain in the butt, thats why I never fixed it previously.  Thank you for fixing it.

**Pull request merged**
