### PR TITLE
Resolved deprecation warning in code

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolve the issue #235 .

### CODE REVIEW

**Comment by introkun** [comment]
@96RadhikaJadhav please provide a PR with a single commit fixing the original issue. I see in your PR 2 commits related to the previous fix. Have you pulled all changes from master to your branch before pushing a PR?

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav please provide a PR with a single commit fixing the original issue. I see in your PR 2 commits related to the previous fix. Have you pulled all changes from master to your branch before pushing a PR?

Oops Sorry! I guess I was working on some other issue and mistakenly done it here. Please ignore this PR. Will create a new one in few mins.

**Comment by 96RadhikaJadhav** [comment]
> > @96RadhikaJadhav please provide a PR with a single commit fixing the original issue. I see in your PR 2 commits related to the previous fix. Have you pulled all changes from master to your branch before pushing a PR?
> 
> Oops Sorry! I guess I was working on some other issue and mistakenly done it here. Please ignore this PR. Will create a new one in few mins.

I have created another PR #275 . Could you please check and let me know if any other changes required.

**Comment by introkun** [comment]
Resolved in #275

**Pull request closed without merging**
